language: php

env:
  - PHALCON_VERSION="2.0.x"
  - PHALCON_VERSION="2.0.0"

before_script:
  - ./tests/install-php-extension.sh ${PHALCON_VERSION}
  - php -r 'echo \Phalcon\Version::get()."\n";'
  - composer self-update
  - composer update

php:
  - 5.4

matrix:
  allow_failures:
    - composer
    - phpunit